version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: agro-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: agrotech
    ports:
      - "5000:5432"
    networks:
      - app-network
    volumes:
      - agro-db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agro-back
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://agrodb:5432/agrotech
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

networks:
  app-network:
    driver: bridge

volumes:
  agro-db-data:
