version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: agro-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: agro-tech
    ports:
      - "5433:5432"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agro-back
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://agrodb:5432/agrotech
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

networks:
  app-network:
    driver: bridge
